name: CI Production Environtment
on:
  push:
    tags:
      - '*.*.*'
env:
  REGISTRY_URL: imagetoolcr.azurecr.io
  IMAGE_NAME: imagetool-frontend

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set env for Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Show version build
        run: |
          echo $RELEASE_VERSION
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker BuildX 1
        id: builder1
        uses: docker/setup-buildx-action@v1
      - name: Set Up Docker BuildX 2
        id: builder2
        uses: docker/setup-buildx-action@v1
      - name: Login to azure container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_AZURE_USERNAME }}
          password: ${{ secrets.REGISTRY_AZURE_TOKEN }}
      - name: Build and Push with tagging
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          context: .
          file: ./Dockerfile.production
          builder: ${{ steps.builder1.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and Push with latest
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          context: .
          file: ./Dockerfile.production
          builder: ${{ steps.builder2.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
